<div align="center"><span style="font-family: Arial; color:#0000FF"><b>
    <span style="font-size: x-large">Métodos Numéricos II</span>
    <br>
    <span style="font-size: large">Segundo de Grado en Matemáticas - Curso 2023/24</span>
    <br>
    <span style="font-size: medium">Facultad de Ciencias de la Universidad de Málaga</span>
    <br>
    <span style="font-size: small">Dpto. de Análisis Matemático, Estadística e Investigación Operativa, y Matemática Aplicada</span>
    <br>
    <span style="font-size: medium; color:#000000">Profs. Manuel J. Castro y Francisco J. Palma (Área Conocimiento de Matemática Aplicada)</span>
    <br>
    <span style="font-size: medium; color:#FF0000">Práctica número 2</span>
    </b></span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    En primer lugar cargamos los módulos necesarios.
    </span></div>

In [1]:
# -*- coding: utf-8 -*-

from numpy import *
from numpy.linalg import *
from numpy import abs, sum, max, min

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    El primer objetivo de esta práctica es ver la forma en la que podemos <b>definir nuestras propias funciones</b> que implementen un determinado algoritmo.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Por ejemplo, nos podemos plantear definir una función, a la que llamaremos <span style="font-family: Courier">conjugada()</span>, que calcule la <b>conjugada</b> de una matriz.
    <br>
    Esta función debe tener un único argumento de entrada, que es una matriz $A\in\mathcal{M}_{m\times n}(\mathbb{C})$, y debe devolver su matriz conjugada $A^*\in\mathcal{M}_{n\times m}(\mathbb{C})$. El código necesario para llevar a cabo esta tarea puede ser tan simple como este que sigue.
    </span></div>

In [2]:
def conjugada(A):
    return conjugate(transpose(A))

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 1.</b></span> Calcular las conjugadas de las matrices: (a) $A = \left( \begin{array}{cc} 1 & 4\,i \\ 2 & -5\,i \\ 3 & 6+6\,i \end{array} \right)$; (b) $B = \left( \begin{array}{cc} 1 & 4\,i \end{array} \right)$; (c) $C = \left( \begin{array}{c} 1 \\ 2 \\ 3 \end{array} \right)$.
    </span></div>

In [4]:
# Ejercicio 1-a.
print("Ejercicio 1-a.")
A = array([[1, 4j], [2, -5j], [3, 6+6j]])#siempre que haya objetos con nunm complejo y reales siempre imprime el mas fuerte, en este caso los complejos, el j es la unidad imaginaria en python
print("Matriz: A = \n", A)
print("Conjugada: A^* = \n", conjugada(A))

Ejercicio 1-a.
Matriz: A = 
 [[ 1.+0.j  0.+4.j]
 [ 2.+0.j -0.-5.j]
 [ 3.+0.j  6.+6.j]]
Conjugada: A^* = 
 [[ 1.-0.j  2.-0.j  3.-0.j]
 [ 0.-4.j -0.+5.j  6.-6.j]]


In [8]:
# Ejercicio 1-b.
print("Ejercicio 1-b.")
B = array([[1, 4j]])#asi es como escribo una fila de unamatriz sino pongo dos cochetes pues sera un vector lo q saco
print("Matriz: B = \n", B)
print("Conjugada: B^* = \n", conjugada(B))

Ejercicio 1-b.
Matriz: B = 
 [[1.+0.j 0.+4.j]]
Conjugada: B^* = 
 [[1.-0.j]
 [0.-4.j]]


In [7]:
# Ejercicio 1-c.
print("Ejercicio 1-c.")
C = array([[1], [2], [3]])
print("Matriz: C = \n", C)
print("Conjugada: C^* = \n", conjugada(C))

Ejercicio 1-c.
Matriz: C = 
 [[1]
 [2]
 [3]]
Conjugada: C^* = 
 [[1 2 3]]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 2.</b></span> Mejorar la función anterior en el siguiente sentido: como se puede comprobar, si el argumento de entrada es un vector (array de una dimensión), la función devuelve también un vector con los elementos conjugados (ello es debido a que la función <span style="font-family: Courier">transpose()</span> actuando sobre un vector no tiene ningún efecto); modificar la función creada para que en este caso considere el vector como una matriz fila y devuelva, por tanto, una matriz columna (evidentemente con los elementos conjugados).
    <br>
    Comprobar la validez de la mejora realizada utilizando el vector $x=(1+i\,,\,2-2\,i\,,\,-3+3\,i)$ (por supuesto, todo lo que funcionaba bien deberá seguir funccionando bien).
    </span></div>

In [51]:
def conjugada(A):
#EN FUNCION SI TENGO UN ONJ SIM 1 O 2 HAGO UNA COSA U OTRA, SI LO Q LE PASO ES UN OBJ DE DIM >2 ENTOCES DOY MENSAJE Q NO LO PUEDO APLICAR
    if ndim(A)>2:
        print ("dimension superior a 2")
        return 0
    elif ndim(A) ==2:
        return conjugate(transpose(A))
    else: 
        return conjugate(transpose([A]))

In [52]:
# Ejercicio 2.
print("Ejercicio 2.")
x = array([1+1j, 2-2j, -3+3j])
print(conjugada (x))

Ejercicio 2.
[[ 1.-1.j]
 [ 2.+2.j]
 [-3.-3.j]]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    El siguiente objetivo de esta práctica es calcular los <b>autovalores</b> y <b>autovectores</b> de una matriz, <b>diagonalizarla</b> (si es posible) y calcular sus <b>valores singulares</b>.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Dada una matriz $A\in\mathcal{M}_n(\mathbb{K})$, sus <b>autovalores</b> y <b>autovectores</b> pueden calcularse con la ayuda de la función <span style="font-family: Courier">eig()</span>; esta función tiene un único argumento de entrada que es la matriz cuadrada $A$ y tiene dos argumentos de salida, siendo el primero un vector de $n$ componentes conteniendo a los autovalores (en un orden arbitrario, quizás números complejos aunque la matriz sea de coeficientes reales y repetidos en caso de multiplicidad mayor que uno) y el segundo una matriz cuadrada de orden $n$ cuyas columnas son autovectores (asociados a los autovalores calculados, en el mismo orden y unitarios respecto del producto escalar ordinario).
    <br>
    No obstante la matriz de autovectores puede no ser regular en el caso de que la matriz dada no sea diagonalizable (los autovectores asociados a autovalores con multiplicidad mayor que 1 no son linealmente independientes).
    <br>
    En el caso de que la matriz dada sí sea diagonalizable, la matriz de autovectores que obtenemos es regular, pero aunque tengamos asegurado que existe una matriz de paso ortogonal-unitaria (al ser la matriz dada normal), la que obtenemos no lo es necesariamente.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 3 (a).</b></span> Calcular los autovalores y autovectores, y ver si es diagonalizable la matriz $A = \left( \begin{array}{rr} 3 & 1 \\ 0 & 1 \end{array} \right)$.
    <br>
    Imprimir el vector de autovalores y la matriz de autovectores (ortogonal-unitaria si es posible) y comprobar si la matriz dada es diagonalizable (comprobar que $P^{-1}\,A\,P=D$ para lo cual se puede utilizar la función <span style="font-family: Courier">inv()</span> que calcula la inversa de la función dada como argumento). 
    </span></div>

In [9]:
# Ejercicio 3-a.
print("Ejercicio 3-a.")
A = array([[3, 1], [0, 1]])
print("Matriz: A = \n", A)
d, P = eig(A)#O#JO EIGVA UN POCO EN CONTRA DE SHUR PQ NO NOS LO DA LOS AUTOVEXTORES Q SEAN ORTONORMAL
#d son los autovalores y P son los autovectores
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = \n", P)
detP = det(P)
print("det(P) = ", detP)
if abs(detP) > 1e-10:#el det no es 0, asi lo veo, miro q sea mayor q un numero muy muy chico
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P
    print("inv(P)@A@P = \n", D)
    print("Comprobación: ", max(abs(D - diag(d))))#debe dar la matriz nula, asi q cojo el maximo elelemento de la matriz
else:#el det es casi q 0 
    print("La matriz no es diagonalizable.")

Ejercicio 3-a.
Matriz: A = 
 [[3 1]
 [0 1]]
Vector de autovalores: d =  [3. 1.]
Matriz de autovectores: P = 
 [[ 1.         -0.4472136 ]
 [ 0.          0.89442719]]
det(P) =  0.8944271909999159
La matriz es diagonalizable.
inv(P)@A@P = 
 [[3. 0.]
 [0. 1.]]
Comprobación:  0.0


In [10]:
# Matriz normal.
normal = A@conjugada(A) - conjugada(A)@A
print("A@A^* - A^*@A = \n", normal)
mv = max(abs(normal))
if mv > 1e-10:
    print("La matriz no es normal.")
else:
    print("La matriz es normal.")

A@A^* - A^*@A = 
 [[ 1 -2]
 [-2 -1]]
La matriz no es normal.


In [11]:
# Matriz de paso ortogonal-unitaria.
n = size(d)
unit = conjugada(P)@P
print("P^*@P = \n", unit)
mv = max(abs(unit - eye(n)))
if mv > 1e-10:
    print("La matriz de paso no es ortogonal-unitaria.")
else:
    print("La matriz de paso es ortogonal-unitaria.")

P^*@P = 
 [[ 1.        -0.4472136]
 [-0.4472136  1.       ]]
La matriz de paso no es ortogonal-unitaria.


In [12]:
# Autovalores y autovectores.
n = size(d)
for i in range(n):
    print("Autovalor: lambda = ", d[i], " Autovector (fila): x = ", P[:, i])

Autovalor: lambda =  3.0  Autovector (fila): x =  [1. 0.]
Autovalor: lambda =  1.0  Autovector (fila): x =  [-0.4472136   0.89442719]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 3 (b).</b></span> Ídem con la matriz $A = \left( \begin{array}{rr} 0 & -2 \\ 2 & 0 \end{array} \right)$.
    </span></div>

In [13]:
# Ejercicio 3-b.
print("Ejercicio 3-b.")
A = array([[0, -2], [2, 0]])
print("Matriz: A = \n", A)
d, P = eig(A)#O#JO EIGVA UN POCO EN CONTRA DE SHUR PQ NO NOS LO DA LOS AUTOVEXTORES Q SEAN ORTONORMAL
#d son los autovalores y P son los autovectores
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = \n", P)
detP = det(P)
print("det(P) = ", detP)
if abs(detP) > 1e-10:#el det no es 0, asi lo veo, miro q sea mayor q un numero muy muy chico
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P
    print("inv(P)@A@P = \n", D)
    print("Comprobación: ", max(abs(D - diag(d))))#debe dar la matriz nula, asi q cojo el maximo elelemento de la matriz, aqui da 4,4e-16 y eso es practicamente 0 asi q perfectp
else:#el det es casi q 0 
    print("La matriz no es diagonalizable.")

Ejercicio 3-b.
Matriz: A = 
 [[ 0 -2]
 [ 2  0]]
Vector de autovalores: d =  [0.+2.j 0.-2.j]
Matriz de autovectores: P = 
 [[ 0.        -0.70710678j  0.        +0.70710678j]
 [-0.70710678+0.j         -0.70710678-0.j        ]]
det(P) =  1j
La matriz es diagonalizable.
inv(P)@A@P = 
 [[0.+2.0000000e+00j 0.+4.4408921e-16j]
 [0.-4.4408921e-16j 0.-2.0000000e+00j]]
Comprobación:  4.440892098500626e-16


In [14]:
# Matriz normal.
# Matriz normal.
normal = A@conjugada(A) - conjugada(A)@A
print("A@A^* - A^*@A = \n", normal)
mv = max(abs(normal))
if mv > 1e-10:
    print("La matriz no es normal.")
else:
    print("La matriz es normal.")

A@A^* - A^*@A = 
 [[0 0]
 [0 0]]
La matriz es normal.


In [15]:
# Matriz de paso ortogonal-unitaria.
# Matriz de paso ortogonal-unitaria.
n = size(d)
unit = conjugada(P)@P
print("P^*@P = \n", unit)
mv = max(abs(unit - eye(n)))
if mv > 1e-10:
    print("La matriz de paso no es ortogonal-unitaria.")
else:
    print("La matriz de paso es ortogonal-unitaria.")

P^*@P = 
 [[1.00000000e+00+0.j 2.22044605e-16+0.j]
 [2.22044605e-16+0.j 1.00000000e+00+0.j]]
La matriz de paso es ortogonal-unitaria.


In [ ]:
# Autovalores y autovectores.
n = size(d)
for i in range(n):
    print("Autovalor: lambda = ", d[i], " Autovector (fila): x = ", P[:, i])

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 3 (c).</b></span> Ídem con la matriz $A = \left( \begin{array}{rrr} 2 & 0 & 2 \\ 0 & 1 & 0 \\ 2 & 0 & -1 \end{array} \right)$.
    </span></div>

In [16]:
# Ejercicio 3-c.
print("Ejercicio 3-c.")
A = array([[2, 0 ,2], [0, 1, 0], [2, 0, -1]])
print("Matriz: A = \n", A)
d, P = eig(A)#O#JO EIGVA UN POCO EN CONTRA DE SHUR PQ NO NOS LO DA LOS AUTOVEXTORES Q SEAN ORTONORMAL
#d son los autovalores y P son los autovectores
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = \n", P)
detP = det(P)
print("det(P) = ", detP)
if abs(detP) > 1e-10:#el det no es 0, asi lo veo, miro q sea mayor q un numero muy muy chico
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P
    print("inv(P)@A@P = \n", D)
    print("Comprobación: ", max(abs(D - diag(d))))#debe dar la matriz nula, asi q cojo el maximo elelemento de la matriz
else:#el det es casi q 0 
    print("La matriz no es diagonalizable.")

Ejercicio 3-c.
Matriz: A = 
 [[ 2  0  2]
 [ 0  1  0]
 [ 2  0 -1]]
Vector de autovalores: d =  [ 3. -2.  1.]
Matriz de autovectores: P = 
 [[ 0.89442719 -0.4472136   0.        ]
 [ 0.          0.          1.        ]
 [ 0.4472136   0.89442719  0.        ]]
det(P) =  -1.0
La matriz es diagonalizable.
inv(P)@A@P = 
 [[ 3.00000000e+00  2.22044605e-16  0.00000000e+00]
 [ 0.00000000e+00 -2.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Comprobación:  2.220446049250313e-16


In [17]:
# Matriz normal.
normal = A@conjugada(A) - conjugada(A)@A
print("A@A^* - A^*@A = \n", normal)
mv = max(abs(normal))
if mv > 1e-10:
    print("La matriz no es normal.")
else:
    print("La matriz es normal.")

A@A^* - A^*@A = 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
La matriz es normal.


In [18]:
# Matriz de paso ortogonal-unitaria.
n = size(d)
unit = conjugada(P)@P
print("P^*@P = \n", unit)
mv = max(abs(unit - eye(n)))
if mv > 1e-10:
    print("La matriz de paso no es ortogonal-unitaria.")
else:
    print("La matriz de paso es ortogonal-unitaria.")

P^*@P = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
La matriz de paso es ortogonal-unitaria.


In [19]:
# Autovalores y autovectores.
n = size(d)
for i in range(n):
    print("Autovalor: lambda = ", d[i], " Autovector (fila): x = ", P[:, i])

Autovalor: lambda =  3.0  Autovector (fila): x =  [0.89442719 0.         0.4472136 ]
Autovalor: lambda =  -2.0  Autovector (fila): x =  [-0.4472136   0.          0.89442719]
Autovalor: lambda =  1.0  Autovector (fila): x =  [0. 1. 0.]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 3 (d).</b></span> Ídem con la matriz $A = \left( \begin{array}{rrr} 1 & 0 & 0 \\ -3 & 1 & 0 \\ 4 & -7 & 1 \end{array} \right)$.
    </span></div>

In [20]:
# Ejercicio 3-d.
print("Ejercicio 3-d.")
A = array([[1, 0 ,0], [-3, 1, 0], [4, -7, 1]])
print("Matriz: A = \n", A)
d, P = eig(A)#O#JO EIGVA UN POCO EN CONTRA DE SHUR PQ NO NOS LO DA LOS AUTOVEXTORES Q SEAN ORTONORMAL
#d son los autovalores y P son los autovectores
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = \n", P)
detP = det(P)
print("det(P) = ", detP)
if abs(detP) > 1e-10:#el det no es 0, asi lo veo, miro q sea mayor q un numero muy muy chico
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P
    print("inv(P)@A@P = \n", D)
    print("Comprobación: ", max(abs(D - diag(d))))#debe dar la matriz nula, asi q cojo el maximo elelemento de la matriz
else:#el det es casi q 0 
    print("La matriz no es diagonalizable.")

Ejercicio 3-d.
Matriz: A = 
 [[ 1  0  0]
 [-3  1  0]
 [ 4 -7  1]]
Vector de autovalores: d =  [1. 1. 1.]
Matriz de autovectores: P = 
 [[0.00000000e+00 0.00000000e+00 2.34780031e-33]
 [0.00000000e+00 3.17206578e-17 3.17206578e-17]
 [1.00000000e+00 1.00000000e+00 1.00000000e+00]]
det(P) =  -7.447377042542653e-50
La matriz no es diagonalizable.


In [21]:
# Autovalores y autovectores.
n = size(d)
for i in range(n):
    print("Autovalor: lambda = ", d[i], " Autovector (fila): x = ", P[:, i])

Autovalor: lambda =  1.0  Autovector (fila): x =  [0. 0. 1.]
Autovalor: lambda =  1.0  Autovector (fila): x =  [0.00000000e+00 3.17206578e-17 1.00000000e+00]
Autovalor: lambda =  1.0  Autovector (fila): x =  [2.34780031e-33 3.17206578e-17 1.00000000e+00]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 3 (e).</b></span> Ídem con la matriz $A = \left( \begin{array}{rrrr} 1 & 0 & 0 & 1 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & -2 \\ 1 & 0 & -2 & 5 \end{array} \right)$.
    </span></div>

In [22]:
# Ejercicio 3-e.
print("Ejercicio 3-e.")
A = array([[1, 0 ,0, 1], [0, 1, 0, 0], [0, 0, 1, -2], [1, 0, -2, 5]])
print("Matriz: A = \n", A)
d, P = eig(A)#O#JO EIGVA UN POCO EN CONTRA DE SHUR PQ NO NOS LO DA LOS AUTOVEXTORES Q SEAN ORTONORMAL
#d son los autovalores y P son los autovectores
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = \n", P)
detP = det(P)
print("det(P) = ", detP)
if abs(detP) > 1e-10:#el det no es 0, asi lo veo, miro q sea mayor q un numero muy muy chico
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P
    print("inv(P)@A@P = \n", D)
    print("Comprobación: ", max(abs(D - diag(d))))#debe dar la matriz nula, asi q cojo el maximo elelemento de la matriz
else:#el det es casi q 0 
    print("La matriz no es diagonalizable.")

Ejercicio 3-e.
Matriz: A = 
 [[ 1  0  0  1]
 [ 0  1  0  0]
 [ 0  0  1 -2]
 [ 1  0 -2  5]]
Vector de autovalores: d =  [6.00000000e+00 1.00000000e+00 2.19829378e-18 1.00000000e+00]
Matriz de autovectores: P = 
 [[-1.82574186e-01  8.94427191e-01 -4.08248290e-01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]
 [ 3.65148372e-01  4.47213595e-01  8.16496581e-01  0.00000000e+00]
 [-9.12870929e-01 -1.44829196e-16  4.08248290e-01  0.00000000e+00]]
det(P) =  -1.0
La matriz es diagonalizable.
inv(P)@A@P = 
 [[ 6.00000000e+00  3.49172965e-16 -4.44089210e-16  0.00000000e+00]
 [ 8.47339085e-16  1.00000000e+00  9.63649967e-18  0.00000000e+00]
 [-5.47284775e-16  1.98602732e-16 -1.35973996e-16  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Comprobación:  3.552713678800501e-15


In [23]:
# Matriz normal.
normal = A@conjugada(A) - conjugada(A)@A
print("A@A^* - A^*@A = \n", normal)
mv = max(abs(normal))
if mv > 1e-10:
    print("La matriz no es normal.")
else:
    print("La matriz es normal.")

A@A^* - A^*@A = 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
La matriz es normal.


In [24]:
# Matriz de paso ortogonal-unitaria.
n = size(d)
unit = conjugada(P)@P
print("P^*@P = \n", unit)
mv = max(abs(unit - eye(n)))
if mv > 1e-10:
    print("La matriz de paso no es ortogonal-unitaria.")
else:
    print("La matriz de paso es ortogonal-unitaria.")

P^*@P = 
 [[ 1.00000000e+00 -8.98342425e-17  1.66533454e-16  0.00000000e+00]
 [-8.98342425e-17  1.00000000e+00 -1.70148574e-16  0.00000000e+00]
 [ 1.66533454e-16 -1.70148574e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
La matriz de paso es ortogonal-unitaria.


In [25]:
# Autovalores y autovectores.
n = size(d)
for i in range(n):
    print("Autovalor: lambda = ", d[i], " Autovector (fila): x = ", P[:, i])

Autovalor: lambda =  6.0000000000000036  Autovector (fila): x =  [-0.18257419  0.          0.36514837 -0.91287093]
Autovalor: lambda =  1.000000000000001  Autovector (fila): x =  [ 8.94427191e-01  0.00000000e+00  4.47213595e-01 -1.44829196e-16]
Autovalor: lambda =  2.198293782579099e-18  Autovector (fila): x =  [-0.40824829  0.          0.81649658  0.40824829]
Autovalor: lambda =  1.0  Autovector (fila): x =  [0. 1. 0. 0.]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 3 (f).</b></span> Ídem con la matriz $A = \left( \begin{array}{rrrr} 7 & 1 & 1 & 1 \\ 1 & 7 & 1 & 1 \\ 1 & 1 & 7 & 1 \\ 1 & 1 & 1 & 7 \end{array} \right)$.
    </span></div>

In [26]:
# Ejercicio 3-f.
print("Ejercicio 3-f.")
A = ones((4, 4)) + 6*eye(4)#siepre intenta construirte las matrices asi, usando funciones q ya sabes y no haciendolas ahi a mano y tal, en exa construyelas de esta forma asi, se dan para q se construyan usando funciones q ya sabemos
print("Matriz: A = \n", A)
d, P = eig(A)#O#JO EIGVA UN POCO EN CONTRA DE SHUR PQ NO NOS LO DA LOS AUTOVEXTORES Q SEAN ORTONORMAL
#d son los autovalores y P son los autovectores
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = \n", P)
detP = det(P)
print("det(P) = ", detP)
if abs(detP) > 1e-10:#el det no es 0, asi lo veo, miro q sea mayor q un numero muy muy chico
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P
    print("inv(P)@A@P = \n", D)
    print("Comprobación: ", max(abs(D - diag(d))))#debe dar la matriz nula, asi q cojo el maximo elelemento de la matriz
else:#el det es casi q 0 
    print("La matriz no es diagonalizable.")

Ejercicio 3-f.
Matriz: A = 
 [[7. 1. 1. 1.]
 [1. 7. 1. 1.]
 [1. 1. 7. 1.]
 [1. 1. 1. 7.]]
Vector de autovalores: d =  [ 6. 10.  6.  6.]
Matriz de autovectores: P = 
 [[-8.66025404e-01  5.00000000e-01 -1.38076168e-01  2.77253752e-17]
 [ 2.88675135e-01  5.00000000e-01  8.52077481e-01 -2.71923380e-16]
 [ 2.88675135e-01  5.00000000e-01 -3.57000657e-01 -7.07106781e-01]
 [ 2.88675135e-01  5.00000000e-01 -3.57000657e-01  7.07106781e-01]]
det(P) =  0.9872081656510155
La matriz es diagonalizable.
inv(P)@A@P = 
 [[ 6.00000000e+00  1.55431223e-15  3.33066907e-16  2.22044605e-16]
 [ 6.66133815e-16  1.00000000e+01  4.44089210e-16  0.00000000e+00]
 [ 3.33066907e-16  4.44089210e-16  6.00000000e+00 -2.22044605e-16]
 [ 2.22044605e-16  4.44089210e-16 -1.11022302e-15  6.00000000e+00]]
Comprobación:  3.552713678800501e-15


In [27]:
# Matriz normal.
normal = A@conjugada(A) - conjugada(A)@A
print("A@A^* - A^*@A = \n", normal)
mv = max(abs(normal))
if mv > 1e-10:
    print("La matriz no es normal.")
else:
    print("La matriz es normal.")

A@A^* - A^*@A = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
La matriz es normal.


In [28]:
# Matriz de paso ortogonal-unitaria.
n = size(d)
unit = conjugada(P)@P
print("P^*@P = \n", unit)
mv = max(abs(unit - eye(n)))
if mv > 1e-10:
    print("La matriz de paso no es ortogonal-unitaria.")
else:
    print("La matriz de paso es ortogonal-unitaria.")

P^*@P = 
 [[ 1.00000000e+00 -5.55111512e-17  1.59436626e-01 -8.32667268e-17]
 [-5.55111512e-17  1.00000000e+00  1.94289029e-16 -5.55111512e-17]
 [ 1.59436626e-01  1.94289029e-16  1.00000000e+00 -2.22044605e-16]
 [-8.32667268e-17 -5.55111512e-17 -2.22044605e-16  1.00000000e+00]]
La matriz de paso no es ortogonal-unitaria.


In [29]:
# Autovalores y autovectores.
n = size(d)
for i in range(n):
    print("Autovalor: lambda = ", d[i], " Autovector (fila): x = ", P[:, i])

Autovalor: lambda =  6.0  Autovector (fila): x =  [-0.8660254   0.28867513  0.28867513  0.28867513]
Autovalor: lambda =  9.999999999999998  Autovector (fila): x =  [0.5 0.5 0.5 0.5]
Autovalor: lambda =  5.999999999999998  Autovector (fila): x =  [-0.13807617  0.85207748 -0.35700066 -0.35700066]
Autovalor: lambda =  6.0  Autovector (fila): x =  [ 2.77253752e-17 -2.71923380e-16 -7.07106781e-01  7.07106781e-01]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Dada una matriz $A\in\mathcal{M}_n(\mathbb{K})$, sus <b>valores singulares</b> pueden calcularse con la ayuda de la función <span style="font-family: Courier">svd()</span>; esta función tiene un único argumento de entrada que es la matriz cuadrada $A$ y tiene tres argumentos de salida, siendo el segundo un vector de $n$ componentes (reales y mayores o iguales que 0) conteniendo a los valores singulares (en un orden arbitrario y repetidos en caso de multiplicidad mayor que uno) y el primero y tercero las  dos matrices de orden $n$ ortogonales-unitarias de su descomposición en valores singulares.
    <br>
    Si llamamos $S$ a la matriz diagonal cuyos elementos diagonales son los valores singulares de $A$ (en el orden que proporciona la función <span style="font-family: Courier">svd()</span>) y $U$ y $V$ las matrices ortogonales-unitarias que se obtienen como primera y tercera salida de dicha función, se verifica que $U\,S\,V=A \iff U^{-1}\,A\,V^{-1}=S$.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 4 (a).</b></span> Realizar la descomposición en valores singulares de la matriz $A = \left( \begin{array}{rr} 3 & 1 \\ 0 & 1 \end{array} \right)$.
    </span></div>

In [32]:
# Ejercicio 4-a.
print("Ejercicio 4-a.")
A = array([[3, 1], [0, 1]])
print("Matriz: A = \n", A)
U, s, V = svd(A)#da una matri U,otra V y un vector s con los valores singulares que han de ser num reales >=0
print("Vector de valores singulares: s = ", s)
print("Matrices ortogonales-unitarias de la descomposición en valores singulares:")
print("U = \n", U)
print("V = \n", V)
DVS = U@diag(s)@V
print("U@diag(s)@V = \n", DVS)
print("Comprobación: ", max(abs(DVS - A)))
DVS1 = conjugada(U)@A@conjugada(V)
print("U^{-1}@A@V^{-1} = \n", DVS1)
print("Comprobación: ", max(abs(DVS1 - diag(s))))

Ejercicio 4-a.
Matriz: A = 
 [[3 1]
 [0 1]]
Vector de valores singulares: s =  [3.1795868  0.94351882]
Matrices ortogonales-unitarias de la descomposición en valores singulares:
U = 
 [[ 0.99402894 -0.10911677]
 [ 0.10911677  0.99402894]]
V = 
 [[ 0.93788501  0.34694625]
 [-0.34694625  0.93788501]]
U@diag(s)@V = 
 [[3. 1.]
 [0. 1.]]
Comprobación:  8.881784197001252e-16
U^{-1}@A@V^{-1} = 
 [[ 3.17958680e+00 -2.22044605e-16]
 [ 5.55111512e-17  9.43518824e-01]]
Comprobación:  4.440892098500626e-16


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 4 (b).</b></span> Ídem con la matriz $A = \left( \begin{array}{rr} 0 & -2 \\ 2 & 0 \end{array} \right)$.
    </span></div>

In [33]:
# Ejercicio 4-b.
print("Ejercicio 4-b.")
A = array([[0, -2], [2, 0]])
print("Matriz: A = \n", A)
U, s, V = svd(A)#da una matri U,otra V y un vector s con los valores singulares que han de ser num reales >=0
print("Vector de valores singulares: s = ", s)
print("Matrices ortogonales-unitarias de la descomposición en valores singulares:")
print("U = \n", U)
print("V = \n", V)
DVS = U@diag(s)@V
print("U@diag(s)@V = \n", DVS)
print("Comprobación: ", max(abs(DVS - A)))
DVS1 = conjugada(U)@A@conjugada(V)
print("U^{-1}@A@V^{-1} = \n", DVS1)
print("Comprobación: ", max(abs(DVS1 - diag(s))))

Ejercicio 4-b.
Matriz: A = 
 [[ 0 -2]
 [ 2  0]]
Vector de valores singulares: s =  [2. 2.]
Matrices ortogonales-unitarias de la descomposición en valores singulares:
U = 
 [[ 0. -1.]
 [-1.  0.]]
V = 
 [[-1. -0.]
 [ 0.  1.]]
U@diag(s)@V = 
 [[ 0. -2.]
 [ 2.  0.]]
Comprobación:  0.0
U^{-1}@A@V^{-1} = 
 [[2. 0.]
 [0. 2.]]
Comprobación:  0.0


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 4 (c).</b></span> Ídem con la matriz $A = \left( \begin{array}{rrr} 2 & 0 & 2 \\ 0 & 1 & 0 \\ 2 & 0 & -1 \end{array} \right)$.
    </span></div>

In [ ]:
# Ejercicio 4-c.
print("Ejercicio 4-c.")
A = array([[2, 0 ,2], [0, 1, 0], [2, 0, -1]])
print("Matriz: A = \n", A)
U, s, V = svd(A)#da una matri U,otra V y un vector s con los valores singulares que han de ser num reales >=0
print("Vector de valores singulares: s = ", s)
print("Matrices ortogonales-unitarias de la descomposición en valores singulares:")
print("U = \n", U)
print("V = \n", V)
DVS = U@diag(s)@V
print("U@diag(s)@V = \n", DVS)
print("Comprobación: ", max(abs(DVS - A)))
DVS1 = conjugada(U)@A@conjugada(V)
print("U^{-1}@A@V^{-1} = \n", DVS1)
print("Comprobación: ", max(abs(DVS1 - diag(s))))

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 4 (d).</b></span> Ídem con la matriz $A = \left( \begin{array}{rrr} 1 & 0 & 0 \\ -3 & 1 & 0 \\ 4 & -7 & 1 \end{array} \right)$.
    </span></div>

In [ ]:
# Ejercicio 4-d.
print("Ejercicio 4-d.")
A = array([[1, 0 ,0], [-3, 1, 0], [4, -7, 1]])
print("Matriz: A = \n", A)
U, s, V = svd(A)#da una matri U,otra V y un vector s con los valores singulares que han de ser num reales >=0
print("Vector de valores singulares: s = ", s)
print("Matrices ortogonales-unitarias de la descomposición en valores singulares:")
print("U = \n", U)
print("V = \n", V)
DVS = U@diag(s)@V
print("U@diag(s)@V = \n", DVS)
print("Comprobación: ", max(abs(DVS - A)))
DVS1 = conjugada(U)@A@conjugada(V)
print("U^{-1}@A@V^{-1} = \n", DVS1)
print("Comprobación: ", max(abs(DVS1 - diag(s))))

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 4 (e).</b></span> Ídem con la matriz $A = \left( \begin{array}{rrrr} 1 & 0 & 0 & 1 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & -2 \\ 1 & 0 & -2 & 5 \end{array} \right)$.
    </span></div>

In [ ]:
# Ejercicio 4-e.
print("Ejercicio 4-e.")
A = array([[1, 0 ,0, 1], [0, 1, 0, 0], [0, 0, 1, -2], [1, 0, -2, 5]])
print("Matriz: A = \n", A)
U, s, V = svd(A)#da una matri U,otra V y un vector s con los valores singulares que han de ser num reales >=0
print("Vector de valores singulares: s = ", s)
print("Matrices ortogonales-unitarias de la descomposición en valores singulares:")
print("U = \n", U)
print("V = \n", V)
DVS = U@diag(s)@V
print("U@diag(s)@V = \n", DVS)
print("Comprobación: ", max(abs(DVS - A)))
DVS1 = conjugada(U)@A@conjugada(V)
print("U^{-1}@A@V^{-1} = \n", DVS1)
print("Comprobación: ", max(abs(DVS1 - diag(s))))

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 4 (f).</b></span> Ídem con la matriz $A = \left( \begin{array}{rrrr} 7 & 1 & 1 & 1 \\ 1 & 7 & 1 & 1 \\ 1 & 1 & 7 & 1 \\ 1 & 1 & 1 & 7 \end{array} \right)$.
    </span></div>

In [ ]:
# Ejercicio 4-f.
print("Ejercicio 4-f.")
A = ones((4, 4)) + 6*eye(4)
print("Matriz: A = \n", A)
U, s, V = svd(A)#da una matri U,otra V y un vector s con los valores singulares que han de ser num reales >=0
print("Vector de valores singulares: s = ", s)
print("Matrices ortogonales-unitarias de la descomposición en valores singulares:")
print("U = \n", U)
print("V = \n", V)
DVS = U@diag(s)@V
print("U@diag(s)@V = \n", DVS)
print("Comprobación: ", max(abs(DVS - A)))
DVS1 = conjugada(U)@A@conjugada(V)
print("U^{-1}@A@V^{-1} = \n", DVS1)
print("Comprobación: ", max(abs(DVS1 - diag(s))))

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 5.</b></span> En aquellos casos del Ejercicio 3 en los que hay autovalores con multiplicidad (dimensión algebraica) mayor que 1, comprobar cuando la dimensión geométrica de los mismos es igual o no (y por tanto la matriz es o no diagonalizable).
    <br>
    <i>Indicación:</i> la función <span style="font-family: Courier">matrix_rank()</span>, cuyo parámetro de entrada es una matriz (no necesariamente cuadrada), devuelve el rango de la misma.
    </span></div>

In [34]:
# Ejercicio 5. Caso del ejercicio 3-d.
print("Ejercicio 5 - 3-d.")#matrixrank te da el rango de la matriz
A = array([[1, 0 ,0], [-3, 1, 0], [4, -7, 1]])
print("Matriz: A = \n", A)
d, P = eig(A)
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = \n", P)
detP = det(P)
print("det(P) = ", detP)
if abs(detP) > 1e-10:
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P
    print("inv(P)@A@P = \n", D)
    print("Comprobación: ", max(abs(D - diag(d))))
else:
    print("La matriz no es diagonalizable.")

Ejercicio 5 - 3-d.
Matriz: A = 
 [[ 1  0  0]
 [-3  1  0]
 [ 4 -7  1]]
Vector de autovalores: d =  [1. 1. 1.]
Matriz de autovectores: P = 
 [[0.00000000e+00 0.00000000e+00 2.34780031e-33]
 [0.00000000e+00 3.17206578e-17 3.17206578e-17]
 [1.00000000e+00 1.00000000e+00 1.00000000e+00]]
det(P) =  -7.447377042542653e-50
La matriz no es diagonalizable.


In [35]:
# Ejercicio 5. Caso del ejercicio 3-d.
da = 3#la multplicidad algbraica del autovalor 1 es 3, cojo la multiplicidad del autovalor q sea doble,triple,cuatriplq son las q da problema
print("El autovalor 1 tiene multiplicidad (dimensión algebraica) ", da)
dg = matrix_rank(P)#rango es la dimension geometrica
print("Su dimensión geométrica es ", dg)
if da == dg:
    print("Por tanto la matriz es diagonalizable.")
else:
    print("Por tanto la matriz no es diagonalizable.")

El autovalor 1 tiene multiplicidad (dimensión algebraica)  3
Su dimensión geométrica es  1
Por tanto la matriz no es diagonalizable.


In [36]:
# Ejercicio 5. Caso del ejercicio 3-e.
print("Ejercicio 5 - 3-e.")
A = array([[1, 0 ,0, 1], [0, 1, 0, 0], [0, 0, 1, -2], [1, 0, -2, 5]])
print("Matriz: A = \n", A)
d, P = eig(A)
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = \n", P)
detP = det(P)
print("det(P) = ", detP)
if abs(detP) > 1e-10:
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P
    print("inv(P)@A@P = \n", D)
    print("Comprobación: ", max(abs(D - diag(d))))
else:
    print("La matriz no es diagonalizable.")

Ejercicio 5 - 3-e.
Matriz: A = 
 [[ 1  0  0  1]
 [ 0  1  0  0]
 [ 0  0  1 -2]
 [ 1  0 -2  5]]
Vector de autovalores: d =  [6.00000000e+00 1.00000000e+00 2.19829378e-18 1.00000000e+00]
Matriz de autovectores: P = 
 [[-1.82574186e-01  8.94427191e-01 -4.08248290e-01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]
 [ 3.65148372e-01  4.47213595e-01  8.16496581e-01  0.00000000e+00]
 [-9.12870929e-01 -1.44829196e-16  4.08248290e-01  0.00000000e+00]]
det(P) =  -1.0
La matriz es diagonalizable.
inv(P)@A@P = 
 [[ 6.00000000e+00  3.49172965e-16 -4.44089210e-16  0.00000000e+00]
 [ 8.47339085e-16  1.00000000e+00  9.63649967e-18  0.00000000e+00]
 [-5.47284775e-16  1.98602732e-16 -1.35973996e-16  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Comprobación:  3.552713678800501e-15


In [38]:
# Ejercicio 5. Caso del ejercicio 3-e.
da = 2#multiplicidad doble del 2
print("El autovalor 1 tiene multiplicidad (dimensión algebraica) ", da)
dg = matrix_rank(P[:, 1::2])#cojo la colu 1 y la 3 q realmente es la 2 y la 4 que son las q ocupa el autovalor multiple 1
print("Su dimensión geométrica es ", dg)
if da == dg:
    print("Por tanto la matriz es diagonalizable.")
else:
    print("Por tanto la matriz no es diagonalizable.")

El autovalor 1 tiene multiplicidad (dimensión algebraica)  2
Su dimensión geométrica es  2
Por tanto la matriz es diagonalizable.


In [37]:
# Ejercicio 5. Caso del ejercicio 3-f.
print("Ejercicio 5 - 3-f.")
A = ones((4, 4)) + 6*eye(4)
print("Matriz: A = \n", A)
d, P = eig(A)
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = \n", P)
detP = det(P)
print("det(P) = ", detP)
if abs(detP) > 1e-10:
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P
    print("inv(P)@A@P = \n", D)
    print("Comprobación: ", max(abs(D - diag(d))))
else:
    print("La matriz no es diagonalizable.")

Ejercicio 5 - 3-f.
Matriz: A = 
 [[7. 1. 1. 1.]
 [1. 7. 1. 1.]
 [1. 1. 7. 1.]
 [1. 1. 1. 7.]]
Vector de autovalores: d =  [ 6. 10.  6.  6.]
Matriz de autovectores: P = 
 [[-8.66025404e-01  5.00000000e-01 -1.38076168e-01  2.77253752e-17]
 [ 2.88675135e-01  5.00000000e-01  8.52077481e-01 -2.71923380e-16]
 [ 2.88675135e-01  5.00000000e-01 -3.57000657e-01 -7.07106781e-01]
 [ 2.88675135e-01  5.00000000e-01 -3.57000657e-01  7.07106781e-01]]
det(P) =  0.9872081656510155
La matriz es diagonalizable.
inv(P)@A@P = 
 [[ 6.00000000e+00  1.55431223e-15  3.33066907e-16  2.22044605e-16]
 [ 6.66133815e-16  1.00000000e+01  4.44089210e-16  0.00000000e+00]
 [ 3.33066907e-16  4.44089210e-16  6.00000000e+00 -2.22044605e-16]
 [ 2.22044605e-16  4.44089210e-16 -1.11022302e-15  6.00000000e+00]]
Comprobación:  3.552713678800501e-15


In [39]:
# Ejercicio 5. Caso del ejercicio 3-f.
da = ...
print("El autovalor 1 tiene multiplicidad (dimensión algebraica) ", da)
dg = matrix_rank(P[:, [0, 2, 3]])
print("Su dimensión geométrica es ", dg)
if da == dg:
    print("Por tanto la matriz es diagonalizable.")
else:
    print("Por tanto la matriz no es diagonalizable.")

El autovalor 1 tiene multiplicidad (dimensión algebraica)  Ellipsis
Su dimensión geométrica es  3
Por tanto la matriz no es diagonalizable.


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 6.</b></span> En aquellos casos del Ejercicio 3 en los que la matriz es normal y por tanto diagonalizable con matriz de paso unitaria, pero la matriz de paso obtenida no lo es, obtener una nueva matriz de paso que sí lo sea.
    <br>
    <i>Indicación:</i> la función <span style="font-family: Courier">qr()</span>, cuyo parámetro de entrada es una matriz (no necesariamente cuadrada), devuelve dos matrices, siendo la primera de ellas la ortonormalización de Gram-Schmidt de los vectores columnas de la matriz dada.
    </span></div>

In [30]:
# Ejercicio 6. Caso del ejercicio 3-f.esto era lo qhacia antes y si los autovalores son multiples pues la matri d paso puede no ser unit la q me genere eig
print("Ejercicio 6 - 3-f.")
A = ones((4, 4)) + 6*eye(4)
print("Matriz: A = \n", A)
d, P = eig(A)
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = \n", P)
detP = det(P)
print("det(P) = ", detP)
if abs(detP) > 1e-10:
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P
    print("inv(P)@A@P = \n", D)
    print("Comprobación: ", max(abs(D - diag(d))))
else:
    print("La matriz no es diagonalizable.")

Ejercicio 6 - 3-f.
Matriz: A = 
 [[7. 1. 1. 1.]
 [1. 7. 1. 1.]
 [1. 1. 7. 1.]
 [1. 1. 1. 7.]]
Vector de autovalores: d =  [ 6. 10.  6.  6.]
Matriz de autovectores: P = 
 [[-8.66025404e-01  5.00000000e-01 -1.38076168e-01  2.77253752e-17]
 [ 2.88675135e-01  5.00000000e-01  8.52077481e-01 -2.71923380e-16]
 [ 2.88675135e-01  5.00000000e-01 -3.57000657e-01 -7.07106781e-01]
 [ 2.88675135e-01  5.00000000e-01 -3.57000657e-01  7.07106781e-01]]
det(P) =  0.9872081656510155
La matriz es diagonalizable.
inv(P)@A@P = 
 [[ 6.00000000e+00  1.55431223e-15  3.33066907e-16  2.22044605e-16]
 [ 6.66133815e-16  1.00000000e+01  4.44089210e-16  0.00000000e+00]
 [ 3.33066907e-16  4.44089210e-16  6.00000000e+00 -2.22044605e-16]
 [ 2.22044605e-16  4.44089210e-16 -1.11022302e-15  6.00000000e+00]]
Comprobación:  3.552713678800501e-15


In [31]:
# Ejercicio 6. Caso del ejercicio 3-f.uso qr y saco matriz de paso ortounit a partir de la matriz de paso de eig
q, r  = qr(P[:, [0, 2, 3]])##auto q me dan prob, cojo la primera colu,la3 y la 4 q son las qm e dan prob, en q tengo los tres vectores a los q le he aplicado el procedimiento de orto de gran schmid
U = array(P)#matriz q sea igual que p
U[:, [0, 2, 3]] = q[:, :]#en la colu 1,3,4 pongo los autovectores ortonormalizados
print("Matriz de paso ortogonal-unitaria: U = \n", U)
D = conjugada(U)@A@U
print("Diagonalización: U^*@A@U = \n", D)
print("Comprobación: ", max(abs(D - diag(d))))

Matriz de paso ortogonal-unitaria: U = 
 [[-8.66025404e-01  5.00000000e-01 -1.55377828e-16 -1.45543964e-17]
 [ 2.88675135e-01  5.00000000e-01 -8.16496581e-01 -4.81663352e-17]
 [ 2.88675135e-01  5.00000000e-01  4.08248290e-01 -7.07106781e-01]
 [ 2.88675135e-01  5.00000000e-01  4.08248290e-01  7.07106781e-01]]
Diagonalización: U^*@A@U = 
 [[ 6.00000000e+00  8.88178420e-16  3.33066907e-16 -2.22044605e-16]
 [ 0.00000000e+00  1.00000000e+01 -2.66453526e-15 -4.44089210e-16]
 [ 1.11022302e-16 -2.66453526e-15  6.00000000e+00  0.00000000e+00]
 [-4.44089210e-16 -8.88178420e-16 -6.66133815e-16  6.00000000e+00]]
Comprobación:  3.552713678800501e-15


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 7.</b></span> Para la matriz $A = \left( \begin{array}{rrr} 1 & 2 & 3 \\ 4 & 5 & 6\\ 7 & 8 & 9 \end{array} \right)$, comprobar que los valores singulares de $A$ son efectivamente las raíces cuadradas positivas de los autovalores de $A^*\,A$.
    </span></div>

In [42]:
# Ejercicio 7.
print("Ejercicio 7.")
A = array([[1, 2 ,3], [4, 5, 6], [7, 8, 9]])
B=conjugada(A)@A
#calcu  autovalores de A, le hago su raiz cuadrada y esos son los autovalores de A y luego comprobarlo con el svd y ver si svd funciona bien
print("Matriz: A = \n", A)
d, P = eig(B)#O#JO EIGVA UN POCO EN CONTRA DE SHUR PQ NO NOS LO DA LOS AUTOVEXTORES Q SEAN ORTONORMAL
#d son los autovalores y P son los autovectores
print("Vector de autovalores: d = ", d)
vs=sqrt(d)
print(max(abs(vs-s)))
print("Vector de valores singulares:  ", vs)
U, s, V = svd(A)
print ("usando svd",s)

Ejercicio 7.
Matriz: A = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Vector de autovalores: d =  [2.83858587e+02 1.14141342e+00 2.03995424e-15]
4.516585222993457e-08
Vector de valores singulares:   [1.68481034e+01 1.06836951e+00 4.51658526e-08]
usando svd [1.68481034e+01 1.06836951e+00 3.33475287e-16]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Importante.</b></span> Durante el desarrollo de las clases prácticas vamos a crear un fichero <span style="font-family: Courier">Python</span>, al que daremos el nombre de <span style="font-family: Courier">algoritmos.py</span>, donde almacenaremos todas aquellas funciones propias que definamos durante el curso; esta será la <b>biblioteca</b> de nuestras funciones. A partir de ese momento, podremos utilizar dichas funciones en cualquier hoja de trabajo que estemos utilizando, sin más que importar dicho fichero al principio de la hoja de trabajo con una instrucción del tipo <span style="font-family: Courier">from algoritmos import *</span>.
    <br>
    Cada vez que se modifique dicho fichero, no debemos olvidar guardar su contenido y reinicializar el núcleo de la hoja de trabajo para tener en cuenta dichas modificaciones.
    </span></div>