<div align="center"><span style="font-family: Arial; color:#0000FF"><b>
    <span style="font-size: x-large">Métodos Numéricos II</span>
    <br>
    <span style="font-size: large">Segundo de Grado en Matemáticas - Curso 2023/24</span>
    <br>
    <span style="font-size: medium">Facultad de Ciencias de la Universidad de Málaga</span>
    <br>
    <span style="font-size: small">Dpto. de Análisis Matemático, Estadística e Investigación Operativa, y Matemática Aplicada</span>
    <br>
    <span style="font-size: medium; color:#000000">Profs. Manuel J. Castro y Francisco J. Palma (Área Conocimiento de Matemática Aplicada)</span>
    <br>
    <span style="font-size: medium; color:#FF0000">Práctica número 1</span>
    </b></span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Para el <b>desarrollo de las prácticas de esta asignatura</b> usaremos de forma habitual la biblioteca <span style="font-family: Courier">NumPy</span>.
    <br>
    <span style="font-family: Courier">NumPy</span> (<i>Numerical Python</i>) es una biblioteca de código abierto de <span style="font-family: Courier">Python</span> que se utiliza en casi todos los campos de la ciencia y la ingeniería. Es el estándar universal para trabajar con datos numéricos en <span style="font-family: Courier">Python</span> y es el núcleo de los sistemas científicos de <span style="font-family: Courier">Python</span> y <span style="font-family: Courier">PyData</span>.
    <br>
    La biblioteca <span style="font-family: Courier">NumPy</span> permite trabajar con <b>matrices multidimensionales homogéneas</b> y proporciona una enorme <b>biblioteca de funciones matemáticas</b> de alto nivel que garantizan cálculos eficientes con vectores y matrices.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Todas las prácticas que realicemos deben comenzar con las instrucciones que siguen a continuación que permiten utilizar la codificación <span style="font-family: Courier">utf-8</span> (uso de tildes y otros caracteres especiales) y usar las funciones definidas en los módulos <span style="font-family: Courier">numpy</span> y <span style="font-family: Courier">numpy.linalg</span>, donde se encuentran la mayoría de los comandos utilizados.
    </span></div>

In [3]:
# -*- coding: utf-8 -*-

from numpy import *
from numpy.linalg import *
from numpy import abs, sum, max, min

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Las <b>variables</b> que utilizamos (elementos de los vectores y las matrices) pueden ser <b>enteras</b>, <b>reales</b> (caracterizadas por la presencia del punto decimal o por el uso de la notación científica) o <b>complejas</b> (la unidad imaginaria se designa por <span style="font-family: Courier">j</span>, y debe ir precedida por la parte imaginaria del número complejo sin espacio intermedio); el <b>tipo</b> de la variable se obtiene con la función <span style="font-family: Courier">type()</span>. Todo número entero se puede convertir en real con la <b>función</b> <span style="font-family: Courier">float()</span>, mientras que todo número entero o real se puede convertir en complejo con la <b>función</b> <span style="font-family: Courier">complex()</span>. Respecto a los números complejos están disponibles, entre otras, las <b>funciones</b> <span style="font-family: Courier">real()</span>, <span style="font-family: Courier">imag()</span>, <span style="font-family: Courier">abs()</span>, <span style="font-family: Courier">angle()</span>, <span style="font-family: Courier">conj()</span> y <span style="font-family: Courier">exp()</span>, todas ellas con un significado obvio.
    </span></div>

In [2]:
# Tipos de variables.#hay q ir ejecutando uno por uno para no dejarme cosas sin ejecutar q luego se usan y me daran error
#en examen puedo usar todo lo de clase
i = 4
print("Entero: ", i, " de tipo ", type(i))
print("Real: ", float(i), " de tipo ", type(float(i)))
print("Complejo: ", complex(i), " de tipo ", type(complex(i)))#la unidad compleja es el j y no el i en python

Entero:  4  de tipo  <class 'int'>
Real:  4.0  de tipo  <class 'float'>
Complejo:  (4+0j)  de tipo  <class 'complex'>


In [3]:
r1 = 5.#asi hago q un entero sea un real poniendole el . tb podria poner 5.00
print("Real: ", r1, " de tipo ", type(r1))
print("Complejo: ", complex(r1), " de tipo ", type(complex(r1)))

Real:  5.0  de tipo  <class 'float'>
Complejo:  (5+0j)  de tipo  <class 'complex'>


In [4]:
r2 = 6e0#=6
print("Real: ", r2, " de tipo ", type(r2))
print("Complejo: ", complex(r2), " de tipo ", type(complex(r2)))

Real:  6.0  de tipo  <class 'float'>
Complejo:  (6+0j)  de tipo  <class 'complex'>


In [5]:
c = 4+3j#se usa la j para la unidad imaginaria
print("Complejo: ", c, " de tipo ", type(c))

Complejo:  (4+3j)  de tipo  <class 'complex'>


In [7]:
# Funciones de variable compleja.
z = complex(input("Introduce un número complejo (no nulo): "))#me pide por pantalla un num complejo
print("Complejo introducido: ", z, " de tipo ", type(z))

Introduce un número complejo (no nulo): 2+1j
Complejo introducido:  (2+1j)  de tipo  <class 'complex'>


In [8]:
x = real(z)
y = imag(z)
modulo = abs(z)
argumento = angle(z)
conjugado = conj(z)
print("El número complejo ", z, " tiene parte real ", x,", parte imaginaria ", y, ", módulo ", modulo, ", argumento ", 
      argumento, " radianes, su conjugado es ", conjugado, ", su opuesto es ", -z, " y su inverso es ", z**(-1), ".")
print("Su exponencial vale ", exp(z), ".")

El número complejo  (2+1j)  tiene parte real  2.0 , parte imaginaria  1.0 , módulo  2.23606797749979 , argumento  0.4636476090008061  radianes, su conjugado es  (2-1j) , su opuesto es  (-2-1j)  y su inverso es  (0.4-0.2j) .
Su exponencial vale  (3.992324048441272+6.217676312367968j) .


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Para definir un <b>vector</b> (fila) o una <b>matriz</b> utilizamos la <b>función</b> <span style="font-family: Courier">array()</span> cuyo <b>primer argumento</b> son los elementos del <span style="font-family: Courier">array</span>, separados por comas, encerrados entre corchetes y, en el caso de las matrices, las filas encerradas entre otros corchetes y también separadas por comas. La <b>función</b> <span style="font-family: Courier">print()</span> permite imprimirlos en pantalla. La <b>clase</b> a la que pertenecen (<span style="font-family: Courier">numpy.ndarray</span>) se obtiene con la <b>función</b> <span style="font-family: Courier">type()</span>, el <b>número de dimensiones</b> (1 en el caso de vectores y 2 en el de matrices) con la <b>función</b> <span style="font-family: Courier">ndim()</span> (también se puede utilizar el <b>comando</b> <span style="font-family: Courier">.ndim</span>), el <b>tamaño</b> (longitud del vector, o filas y columnas de las matrices) con la <b>función</b> <span style="font-family: Courier">shape()</span> (también se puede utilizar el <b>comando</b> <span style="font-family: Courier">.shape</span>), mientras que el <b>número total de elementos</b> (longitud del vector, o producto del número de filas por el de columnas de las matrices) con la <b>función</b> <span style="font-family: Courier">size()</span> (también se puede utilizar el <b>comando</b> <span style="font-family: Courier">.size</span>).
     </span></div>

In [9]:
# Construcción de matrices.
A = array([[1, -2, 3], [-4, 5, -6]])#[[1fila],[2fila]]
x = array([7., -8, 9])#vector
X = array([[7, -8e0, 9]])#vector fila visto como matriz
Y = array([[1j], [-2]])

In [10]:
print("Impresión de las matrices.")
print("A = \n", A)
print("x = ", x)
print("X = \n", X)
print("Y = \n", Y)

Impresión de las matrices.
A = 
 [[ 1 -2  3]
 [-4  5 -6]]
x =  [ 7. -8.  9.]
X = 
 [[ 7. -8.  9.]]
Y = 
 [[ 0.+1.j]
 [-2.+0.j]]


In [11]:
print("Tipo de las matrices.")
print("type(A) = ", type(A))
print("type(x) = ", type(x))
print("type(X) = ", type(X))
print("type(Y) = ", type(Y))

Tipo de las matrices.
type(A) =  <class 'numpy.ndarray'>
type(x) =  <class 'numpy.ndarray'>
type(X) =  <class 'numpy.ndarray'>
type(Y) =  <class 'numpy.ndarray'>


In [12]:
print("Número de dimensiones de las matrices.")#dim 2 =>matriz(o es un vector pero metido en una matriz, como pasa  con los vect colus y filas), dim 1=>vector
print("ndim(A) = ", ndim(A))
print("ndim(x) = ", ndim(x))
print("ndim(X) = ", ndim(X))
print("ndim(Y) = ", ndim(Y))
print(A.ndim, x.ndim, X.ndim, Y.ndim)

Número de dimensiones de las matrices.
ndim(A) =  2
ndim(x) =  1
ndim(X) =  2
ndim(Y) =  2
2 1 2 2


In [13]:
print("Tamaño de las matrices.")#dice matriz de tam 2x3 ,1x3 o si es dim 1 pues tam 3
print("shape(A) = ", shape(A))
print("shape(x) = ", shape(x))
print("shape(X) = ", shape(X))
print("shape(Y) = ", shape(Y))
print(A.shape, x.shape, X.shape, Y.shape)

Tamaño de las matrices.
shape(A) =  (2, 3)
shape(x) =  (3,)
shape(X) =  (1, 3)
shape(Y) =  (2, 1)
(2, 3) (3,) (1, 3) (2, 1)


In [14]:
print("Número de elementos de las matrices.")
print("size(A) = ", size(A))
print("size(x) = ", size(x))
print("size(X) = ", size(X))
print("size(Y) = ", size(Y))
print(A.size, x.size, X.size, Y.size)#es  lo mismo hacer size(x) que x.size, es lo mismo

Número de elementos de las matrices.
size(A) =  6
size(x) =  3
size(X) =  3
size(Y) =  2
6 3 3 2


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Observamos que todos los elementos de un <span style="font-family: Courier">array</span> tienen el mismo <b>tipo</b>, que es el tipo <i>más rico</i> de entre todos sus elementos; para conocer el <b>tipo de los elementos</b> de un <span style="font-family: Courier">array</span> se usa el <b>comando</b> <span style="font-family: Courier">.dtype</span>. No obstante, se puede <i>forzar el tipo de los elementos</i> con el <b>argumento opcional</b> <span style="font-family: Courier">dtype=</span> de la función <span style="font-family: Courier">array()</span>.
    </span></div>

In [15]:
# Tipo de los elementos de las matrices.
print("Tipo de los elementos de las matrices.")#me dice el tipo del elemento mas poderoso , con q haya un float ps saca float:  complez>float>int
print("A.dtype = ", A.dtype)
print("x.dtype = ", x.dtype)
print("X.dtype = ", X.dtype)
print("Y.dtype = ", Y.dtype)

Tipo de los elementos de las matrices.
A.dtype =  int32
x.dtype =  float64
X.dtype =  float64
Y.dtype =  complex128


In [16]:
print("Matriz de tipo predefinido.")
B = array([[1, 2], [3, 4]], dtype=float)#impongo q sea una matriz de floats aunq realemnte la estoy def con int pero lo fuerzo a q sean float
print("B = \n", B)
print("B.dtype = ", B.dtype)

Matriz de tipo predefinido.
B = 
 [[1. 2.]
 [3. 4.]]
B.dtype =  float64


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Se puede <b>crear</b> un <span style="font-family: Courier">array</span> lleno de 0’s con la <b>función</b> <span style="font-family: Courier">zeros()</span> y lleno de 1’s con la <b>función</b> <span style="font-family: Courier">ones()</span>; en ambos casos se debe pasar como <b>argumento</b> el tamaño (<span style="font-family: Courier">shape</span>) del <span style="font-family: Courier">array</span>. Para generar un <span style="font-family: Courier">array</span> con <i>elementos aleatorios</i> siguiendo una distribución uniforme sobre el intervalo [0, 1), la <b>función</b> es <span style="font-family: Courier">random.rand()</span>; esta función lleva tantos <b>argumentos</b> como dimensiones se quiere que tenga el <span style="font-family: Courier">array</span>, con los tamaños correspondientes. La <b>función</b> <span style="font-family: Courier">eye()</span> permite crear una matriz, no necesariamente cuadrada, cuyos elementos son todos 0, excepto los de la diagonal principal que valen 1; si esta función lleva un único <b>argumento</b> se crea una matriz cuadrada de dicho tamaño y si lleva dos una matriz rectangular; esta funcion admite un <b>argumento opcional</b> en la forma <span style="font-family: Courier">k=</span> que permite que la diagonal de 1’s esté <span style="font-family: Courier">k</span> posiciones por encima o por debajo (dependiendo del signo) de la diagonal principal.
    </span></div>

In [17]:
# Matrices especiales.
print("Matriz de 0's.")
C = zeros((3, 2))
print("C = \n", C)
print("C.dtype = ", C.dtype)

Matriz de 0's.
C = 
 [[0. 0.]
 [0. 0.]
 [0. 0.]]
C.dtype =  float64


In [18]:
print("Matriz de 1's.")
D = ones((2, 3))
print("D = \n", D)
print("D.dtype = ", D.dtype)

Matriz de 1's.
D = 
 [[1. 1. 1.]
 [1. 1. 1.]]
D.dtype =  float64


In [19]:
print("Matriz aleatoria.")
E = random.rand(3, 2)#los num aleat me los da entre 0 y 1 y x ello xej para pasar los num aleat al inter 5,-5(si me pide matri aleat de num entre -5 y 5) : multi por amplituddel inter (10) y restarle el extremo(creo q se le resta el extremo)
print("E = \n", E)
print("E.dtype = ", E.dtype)

Matriz aleatoria.
E = 
 [[0.45221281 0.17652395]
 [0.66341836 0.48589411]
 [0.95770764 0.30937593]]
E.dtype =  float64


In [20]:
print("Matriz de diagonal principal de 1's.")
F = eye(2, 3)
print("F = \n", F)
print("F.dtype = ", F.dtype)

Matriz de diagonal principal de 1's.
F = 
 [[1. 0. 0.]
 [0. 1. 0.]]
F.dtype =  float64


In [21]:
print("Matriz de k-diagonal principal de 1's.")
G = eye(3, k=1)#si es eye(1solo num) eso es es q es cuadrada es decir tam esenum*esenum, k=1 significa q uno por encima de diag pone 1
print("G = \n", G)
print("G.dtype = ", G.dtype)

Matriz de k-diagonal principal de 1's.
G = 
 [[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
G.dtype =  float64


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Las <b>funciones</b> <span style="font-family: Courier">arange()</span> y <span style="font-family: Courier">linspace()</span> permiten <b>crear vectores</b> (<span style="font-family: Courier">array</span> de una dimensión) <i>interpolando</i> valores intermedios entre dos extremos; los tres <b>argumentos</b> de la función <span style="font-family: Courier">arange</span> son el extremo inicial del intervalo (cerrado), el extremo final (abierto) y el paso de malla; los tres <b>argumentos</b> de la función <span style="font-family: Courier">linspace</span> son el extremo inicial del intervalo (cerrado), el extremo final (cerrado) y el número total de puntos interpolados. Se pueden <b>crear matrices</b> (<span style="font-family: Courier">array</span> de dos dimensiones) combinando estas funciones con la <b>función</b> <span style="font-family: Courier">reshape()</span>, cuyo primer <b>argumento</b> es un vector y el segundo el tamaño de la matriz que se creará.
    </span></div>

In [7]:
print("Matriz creada por interpolación.")
h = arange(0, 12, 1) #arange me da lista de num [0...12) , ojo q el 0 es incluido y el 12 no es incluido , eso me dice el 1
print("h = ", h)
H = reshape(h, (3, 4))
print("H = \n", H)
print("H.dtype = ", H.dtype)

Matriz creada por interpolación.
h =  [ 0  1  2  3  4  5  6  7  8  9 10 11]
H = 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
H.dtype =  int32


In [23]:
print("Matriz creada por interpolación.")
k = linspace(0, 11, 12)#cojo del 0 al 11 y hago 12 puntos
print("k = ", k)
K = reshape(k, (4, 3))
print("K = \n", K)
print("K.dtype = ", K.dtype)

Matriz creada por interpolación.
k =  [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
K = 
 [[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
K.dtype =  float64


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Se puede <b>acceder a los elementos</b> de un <span style="font-family: Courier">array</span> poniendo sus coordenadas entre corchetes y sabiendo que siempre se numeran desde 0. Se puede <b>acceder a más de un elemento</b> usando la <b>notación</b> <span style="font-family: Courier">a:b</span> o <span style="font-family: Courier">a:b:c</span> que considera todos los índices entre <span style="font-family: Courier">a</span> (incluido) y <span style="font-family: Courier">b</span> (excluido), eventualmente con salto de <span style="font-family: Courier">c</span>; la ausencia de <span style="font-family: Courier">a</span> significa que se consideran todos los índices desde el primero, y la ausencia de <span style="font-family: Courier">b</span> que se consideran todos los índices hasta el último. En el caso de matrices, la presencia de esta notación en uno de los dos índices <b>genera un vector</b>, mientras que la presencia en ambos índices <b>genera una matriz</b> (submatriz de la matriz dada).
    </span></div>

In [24]:
# Acceso a los elementos de las matrices.
print("Acceso a los elementos de las matrices.")
print("A[0, 0] = ", A[0, 0])

Acceso a los elementos de las matrices.
A[0, 0] =  1


In [25]:
print("x[1] = ", x[1])#2elemento, empieza en 0 siempre el indice

x[1] =  -8.0


In [26]:
print("X[0, 1] = ", X[0, 1])

X[0, 1] =  -8.0


In [27]:
print("Y[1, 0] = ", Y[1, 0])

Y[1, 0] =  (-2+0j)


In [28]:
print("A[1, :] = ", A[1, :])#coge en la primera fila todas las colus, es decir dame la primera fila(q en vd es la 2 fila)

A[1, :] =  [-4  5 -6]


In [29]:
print("A[1:, :] = ", A[1:, :])#coge a aprtir de la fila 1  todas la filas(fila 1 es la fila 2 realemente)

A[1:, :] =  [[-4  5 -6]]


In [30]:
print("A[:, 1] = ", A[:, 1])

A[:, 1] =  [-2  5]


In [31]:
print("A[:, 1:2] = ", A[:, 1:2])#cojo de 1 a 2 pero en python en iterador 1argu es cerrado y segundo es abierto asi q estoy cogiendo de 1 a 1

A[:, 1:2] =  [[-2]
 [ 5]]


In [32]:
print("A[:1, 1:] = ", A[:1, 1:])#:1compo, va de 0 hata 1 abierto es decir fila 0, 2compo, de la primera colu cojo hasta en adelante

A[:1, 1:] =  [[-2  3]]


In [33]:
print("A[:, ::2] = ", A[:, ::2])#1comp, todas las filas y todas las colus 

A[:, ::2] =  [[ 1  3]
 [-4 -6]]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Para una matriz, la <b>función</b> <span style="font-family: Courier">transpose()</span> calcula la <b>matriz transpuesta</b> (esta función actuando sobre un vector no tiene efecto), mientras que la <b>función</b> <span style="font-family: Courier">conjugate()</span> solamente <b>conjuga los elementos</b>; por tanto para calcular la <b>matriz conjugada</b> de una matriz compleja hay que combinar ambas funciones.
    </span></div>

In [34]:
# Transposición y conjugación.
print("Transposición y conjugación.")
print("Transpuesta-vector: transpose(x) = ", transpose(x))#si es compleja, pues rtraspose la traspone y no conjuga los elem, solo le camia matriz por fila

Transposición y conjugación.
Transpuesta-vector: transpose(x) =  [ 7. -8.  9.]


In [35]:
print("Transpuesta: transpose(A) = \n", transpose(A))

Transpuesta: transpose(A) = 
 [[ 1 -4]
 [-2  5]
 [ 3 -6]]


In [36]:
print("Conjugada: conjugate(transpose(X)) = \n", conjugate(transpose(X)))

Conjugada: conjugate(transpose(X)) = 
 [[ 7.]
 [-8.]
 [ 9.]]


In [37]:
print("Conjugada: conjugate(transpose(Y)) = \n", conjugate(transpose(Y)))

Conjugada: conjugate(transpose(Y)) = 
 [[ 0.-1.j -2.-0.j]]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Las <b>operaciones elementales</b> (<b>sumas</b> con el <b>operador</b> <span style="font-family: Courier">+</span>, <b>productos</b> con el <b>operador</b> <span style="font-family: Courier">*</span> y <b>potencias</b> con el <b>operador</b> <span style="font-family: Courier,">**</span>) actúan sobre los <span style="font-family: Courier">array</span> elemento a elemento (incluido el producto y la potencia). Indicamos que tanto la suma como el producto admiten dos <b>generalizaciones</b>; por un lado sumar o multiplicar una constante, en cuyo caso suma o multiplica la constante a todos sus elementos (en el caso del producto es el usual producto por escalares); por otro lado sumar o multiplicar un vector (o matriz fila) o una matriz columna a una matriz, en cuyo caso lo suma o multiplica, elemento a elemento, a todas las filas o columnas de la matriz, siempre que las dimensiones lo permiten.
    <br>
    Para utilizar el <b>producto matricial</b> habitual debe utilizarse el <b>operador</b> <span style="font-family: Courier">@</span> y para la <b>potencia de matrices</b> la <b>función</b> <span style="font-family: Courier">matrix_power()</span>.
    <br>
    En cualquier caso, todos los resultados de operaciones entre matrices adopta el tipo <i>más rico</i> de todos los que intervienen en dichos cálculos.
    </span></div>

In [38]:
# Operaciones elementales.
print("Operaciones elementales.")
print("Suma: A + D = \n", A + D)

Operaciones elementales.
Suma: A + D = 
 [[ 2. -1.  4.]
 [-3.  6. -5.]]


In [39]:
print("Suma constante: 3. + A = \n", 3. + A)#sumar 3 a todos los elem aij de la matriz
print("Suma constante: -2 + x = ", -2 + x)

Suma constante: 3. + A = 
 [[ 4.  1.  6.]
 [-1.  8. -3.]]
Suma constante: -2 + x =  [  5. -10.   7.]


In [40]:
print("Suma vector: x + A = \n", x + A)

Suma vector: x + A = 
 [[  8. -10.  12.]
 [  3.  -3.   3.]]


In [41]:
print("Suma matriz fila: X + A = \n", X + A)

Suma matriz fila: X + A = 
 [[  8. -10.  12.]
 [  3.  -3.   3.]]


In [42]:
print("Suma matriz columna: Y + A = \n", Y + A)

Suma matriz columna: Y + A = 
 [[ 1.+1.j -2.+1.j  3.+1.j]
 [-6.+0.j  3.+0.j -8.+0.j]]


In [43]:
print("Producto-elemento: A*D = \n", A*D)#cd pone el * es multiplicar elemento a elemento

Producto-elemento: A*D = 
 [[ 1. -2.  3.]
 [-4.  5. -6.]]


In [44]:
print("Producto escalares: 3*A = \n", 3*A)

Producto escalares: 3*A = 
 [[  3  -6   9]
 [-12  15 -18]]


In [45]:
print("Producto vector: x*A = \n", x*A)

Producto vector: x*A = 
 [[  7.  16.  27.]
 [-28. -40. -54.]]


In [46]:
print("Producto matriz fila: X*A = \n", X*A)

Producto matriz fila: X*A = 
 [[  7.  16.  27.]
 [-28. -40. -54.]]


In [47]:
print("Producto matriz columna: Y*A = \n", Y*A)

Producto matriz columna: Y*A = 
 [[  0.+1.j  -0.-2.j   0.+3.j]
 [  8.-0.j -10.+0.j  12.-0.j]]


In [48]:
print("Producto: A@H = \n", A@H)#este es el producto verdadero matriz por matriz de toda la vida y las matrices han de ser compatibles para poder multiplicarlas

Producto: A@H = 
 [[ 16  18  20  22]
 [-28 -33 -38 -43]]


In [49]:
print("Potencia-elemento: A**3 = \n", A**3)#esta no es la potncia verdadera, esta es potencia elem a elem

Potencia-elemento: A**3 = 
 [[   1   -8   27]
 [ -64  125 -216]]


In [50]:
print("Potencia: matrix_power(B, 2) = \n", matrix_power(B, 2))##esta es la verdadera potencia de amtriz tal y como la conocemos

Potencia: matrix_power(B, 2) = 
 [[ 7. 10.]
 [15. 22.]]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Las <b>funciones</b> <span style="font-family: Courier">tril()</span> y <span style="font-family: Courier">triu()</span> extraen la parte <b>triangular inferior</b> y <b>superior</b>, respectivamente, de la matriz que se da como <b>argumento</b>; estas funciones  admiten un <b>argumento opcional</b> <span style="font-family: Courier">k=</span>, que puede ser positivo o negativo, que permite añadir o suprimir extradiagonales.
    <br>
    Cuando el <b>argumento</b> de estas funciones es un vector, se construye una matriz cuadrada triangular con el vector dado como fila de dicha matriz.
    </span></div>

In [51]:
# Matrices triangulares.
print("Matrices triangulares:")#triang inf es tril
print("tril(A) = \n", tril(A))#hace triang a la matri A
print("tril(A, k=1) = \n", tril(A, k=1))#traingular pero incluyendo un por encima
print("tril(A, k=-1) = \n", tril(A, k=-1))#triang pero incluyendo uno por debajo

Matrices triangulares:
tril(A) = 
 [[ 1  0  0]
 [-4  5  0]]
tril(A, k=1) = 
 [[ 1 -2  0]
 [-4  5 -6]]
tril(A, k=-1) = 
 [[ 0  0  0]
 [-4  0  0]]


In [52]:
print("triu(A) = \n", triu(A))#triang sup es triu
print("triu(A, k=1) = \n", triu(A, k=1))
print("triu(A, k=-1) = \n", triu(A, k=-1))

triu(A) = 
 [[ 1 -2  3]
 [ 0  5 -6]]
triu(A, k=1) = 
 [[ 0 -2  3]
 [ 0  0 -6]]
triu(A, k=-1) = 
 [[ 1 -2  3]
 [-4  5 -6]]


In [53]:
print("tril(x) = \n", tril(x))#tril de un vector x e ir rellenando
print("triu(x) = \n", triu(x))

tril(x) = 
 [[ 7.  0.  0.]
 [ 7. -8.  0.]
 [ 7. -8.  9.]]
triu(x) = 
 [[ 7. -8.  9.]
 [ 0. -8.  9.]
 [ 0.  0.  9.]]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Ciertas <b>funciones usuales</b> actúan sobre <span style="font-family: Courier">array</span> de una forma predecible; será útil comprobar esto considerando tanto vectores como matrices (reales o complejas) y viendo como se transforman mediante la <b>función</b> <span style="font-family: Courier">abs()</span>, cuyo <b>argumento</b> es el <span style="font-family: Courier">array</span> al que se le calcularán los valores absolutos o módulos de sus elementos, y la <b>función</b> <span style="font-family: Courier">sum()</span> cuyo <b>argumento</b> es el <span style="font-family: Courier">array</span> cuyos elementos se sumarán; en el caso de matrices, esta última función admite un <b>argumento opcional</b> en la forma <span style="font-family: Courier">axis=0</span> o <span style="font-family: Courier">axis=1</span>, que permite hacer la suma por columnas o por filas, dando como resultado un vector. Un comportamiento totalmente análogo, incluido el argumento opcional, tienen las <b>funciones</b> <span style="font-family: Courier">max()</span> y <span style="font-family: Courier">min()</span>.
    </span></div>

In [54]:
# Funciones usuales.
print("Funciones usuales.")#abs de complejo me hace el modulo
print("abs(A) = \n", abs(A))
print("abs(x) = ", abs(x))
print("abs(X) = \n", abs(X))
print("abs(Y) = \n", abs(Y))

Funciones usuales.
abs(A) = 
 [[1 2 3]
 [4 5 6]]
abs(x) =  [7. 8. 9.]
abs(X) = 
 [[7. 8. 9.]]
abs(Y) = 
 [[1.]
 [2.]]


In [58]:
print("sum(A) = ", sum(A))
print("sum(A, axis=0) = ", sum(A, axis=0))#da un vector fila unid q resulta de sumar las colus
print("sum(A, axis=1) = ", sum(A, axis=1))#da un vector unid suma filas

sum(A) =  -3
sum(A, axis=0) =  [-3  3 -3]
sum(A, axis=1) =  [ 2 -5]


In [59]:
print("max(A) = ", max(A))
print("max(A, axis=0) = ", max(A, axis=0))
print("max(A, axis=1) = ", max(A, axis=1))

max(A) =  5
max(A, axis=0) =  [1 5 3]
max(A, axis=1) =  [3 5]


In [60]:
print("min(A) = ", min(A))
print("min(A, axis=0) = ", min(A, axis=0))
print("min(A, axis=1) = ", min(A, axis=1))

min(A) =  -6
min(A, axis=0) =  [-4 -2 -6]
min(A, axis=1) =  [-2 -6]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    La <b>función</b> <span style="font-family: Courier">diagflat()</span> permite construir <b>matrices diagonales</b> a partir de los elementos de un vector o de una matriz, que se da como <b>argumento</b>; admite un <b>argumento opcional</b> <span style="font-family: Courier">k=</span> que coloca los elementos <span style="font-family: Courier">k</span> diagonales por arriba o por abajo, dependiendo del signo, de la diagonal principal.
    <br>
    Recíprocamente, cuando la <b>función</b> <span style="font-family: Courier">diag()</span> tiene como <b>argumento</b> una matriz, se extrae en un vector la diagonal principal de la misma; admite el mismo <b>argumento opcional</b> <span style="font-family: Courier">k=</span> con un objetivo análogo. Cuando esta función tienen como argumento un vector el efecto es el mismo que la función anterior.
    </span></div>

In [61]:
print("Matrices diagonales.")
print("diagflat(x) = \n", diagflat(x))#pone en la diag los elem del vector x

Matrices diagonales.
diagflat(x) = 
 [[ 7.  0.  0.]
 [ 0. -8.  0.]
 [ 0.  0.  9.]]


In [62]:
print("diagflat(Y, k=1) = \n", diagflat(Y, k=1))#el Y lo pongo encima de la diagonal

diagflat(Y, k=1) = 
 [[ 0.+0.j  0.+1.j  0.+0.j]
 [ 0.+0.j  0.+0.j -2.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j]]


In [63]:
print("diagflat(A, k=-1) = \n", diagflat(A, k=-1))#pongo matriz como un vector y los pongo diagnal debajo y como matriz tenia 6 elelm ps necesita una matriz dim 7x7 para reallenarla

diagflat(A, k=-1) = 
 [[ 0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0]
 [ 0 -2  0  0  0  0  0]
 [ 0  0  3  0  0  0  0]
 [ 0  0  0 -4  0  0  0]
 [ 0  0  0  0  5  0  0]
 [ 0  0  0  0  0 -6  0]]


In [64]:
print("diag(A) = ", diag(A))

diag(A) =  [1 5]


In [65]:
print("diag(A, k=1) = ", diag(A, k=1))

diag(A, k=1) =  [-2 -6]


In [66]:
print("diag(Y) = ", diag(Y))

diag(Y) =  [0.+1.j]


In [67]:
print("diag(x) = \n", diag(x))

diag(x) = 
 [[ 7.  0.  0.]
 [ 0. -8.  0.]
 [ 0.  0.  9.]]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    También es posible <b>concatenar matrices</b>, tanto horizontal, como verticalmente, con las <b>funciones</b>
<span style="font-family: Courier">hstack()</span> y <span style="font-family: Courier">vstack()</span>; el <b>argumento</b> de estas funciones es la tupla formada por las matrices que se quieren concatenar, cuyas dimensiones deben permitir esta manipulación. También aquí todos los resultados de manipulaciones entre matrices adopta el tipo <i>más rico</i> de todos los que intervienen en dichas manipulaciones.
    </span></div>

In [68]:
print("Matrices concatenadas.")
print("vstack([A, D]) = \n", vstack([A, D]))

Matrices concatenadas.
vstack([A, D]) = 
 [[ 1. -2.  3.]
 [-4.  5. -6.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [69]:
print("hstack([A, B]) = \n", hstack([A, B]))

hstack([A, B]) = 
 [[ 1. -2.  3.  1.  2.]
 [-4.  5. -6.  3.  4.]]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 1.</b></span> Generar una matriz de tamaño 20, que sea tridiagonal con elementos diagonales iguales a 2 y elementos sub-diagonales y supra-diagonales iguales a -1.
    </span></div>

In [24]:
# Ejercicio 1.
print("Ejercicio 1.")#todos los ejs hacerlos sin usar bucle
L=eye(20,20)
Z=2*L
L1=eye(20,k=1)
Z1=-1*L1
L2=eye(20,k=-1)
Z2=-1*L2
Z3=Z+Z1+Z2
print(Z3)

Ejercicio 1.
[[ 2. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [-1.  2. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0. -1.  2. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0. -1.  2. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0. -1.  2. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0. -1.  2. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0. -1.  2. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  2. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  2. -1.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.  2. -1.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  2. -1.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  2. -1

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 2.</b></span> Dada la matriz $A = \left( \begin{array}{cc} 1 & 2 \\ 3 & 4 \end{array} \right)$, construir las matrices $B = \left( \begin{array}{c|c} A & 2\,A \\ \hline 3\,A & 4\,A \end{array} \right)$ y $C = \left( \begin{array}{c|c|c} A & I & \\ \hline I & A & I \\ \hline & I & A \end{array} \right)$. Con la ayuda de la función <span style="font-family: Courier">det()</span>, cuyo único argumento es una matriz cuadrada, calcular los determinantes de las matrices anteriores.
    </span></div>

In [32]:
# Ejercicio 2.
print("Ejercicio 2.")
A=array([[1,2],[3,4]])
B1=hstack([A,2*A])
B2=hstack([3*A,4*A])
B=vstack([B1,B2])
print(det(A))
print(det(B))
AUX=zeros((2,2))
D=eye(2,2)
C1=hstack([A,D])
C2=hstack([C1,AUX])
C3=hstack([D,A])
C4=hstack([C3,D])
C5=hstack([AUX,D])
C6=hstack([C5,A])
C7=vstack([C2,C4])
C8=vstack([C7,C6])
print(det(C8))

Ejercicio 2.
-2.0000000000000004
16.000000000000007
99.99999999999996


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 3.</b></span> Construir una matriz $A=(a_{i,j})\in\mathcal{M}_{10}(\mathbb{R})$ tal que $a_{i,j}=10\,(i-1)+j$, para todo $i,j=1,2,\ldots,10$. Construir también las matrices $B,C\in\mathcal{M}_{10}(\mathbb{R})$ que coinciden con $A$, excepto que en $B$ permutan entre sí las filas y columnas segunda y quinta, y en $C$ a la quinta fila de $A$ se le suma 3 veces la segunda fila.
    </span></div>

In [50]:
# Ejercicio 3.
print("Ejercicio 3.")
A1=arange(1,11,1,dtype=float)-1
A2=10*reshape(A1,(-1,1))#1 colu y las filas q necesite para llenar con el vector A, si pongo reshape de (10,10) me dice q no pq una matriz de 10*10 no la puedo llenar con el vctor de 11 elem q es A, necesitaria un vector de 100 elem para llenarla
A3=arange(1,11)
Z=A2+A3
print(Z)

B = Z
B[[1,4],:] = B[[4,1],:]
B[:,[1,4]] = B[:,[4,1]]
print("B=")
print(B)
print()
C = Z
C[4,:] += 3*C[1,:]
print("C= ")
print(C)

Ejercicio 3.
[[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [ 11.  12.  13.  14.  15.  16.  17.  18.  19.  20.]
 [ 21.  22.  23.  24.  25.  26.  27.  28.  29.  30.]
 [ 31.  32.  33.  34.  35.  36.  37.  38.  39.  40.]
 [ 41.  42.  43.  44.  45.  46.  47.  48.  49.  50.]
 [ 51.  52.  53.  54.  55.  56.  57.  58.  59.  60.]
 [ 61.  62.  63.  64.  65.  66.  67.  68.  69.  70.]
 [ 71.  72.  73.  74.  75.  76.  77.  78.  79.  80.]
 [ 81.  82.  83.  84.  85.  86.  87.  88.  89.  90.]
 [ 91.  92.  93.  94.  95.  96.  97.  98.  99. 100.]]
B=
[[  1.   5.   3.   4.   2.   6.   7.   8.   9.  10.]
 [ 41.  45.  43.  44.  42.  46.  47.  48.  49.  50.]
 [ 21.  25.  23.  24.  22.  26.  27.  28.  29.  30.]
 [ 31.  35.  33.  34.  32.  36.  37.  38.  39.  40.]
 [ 11.  15.  13.  14.  12.  16.  17.  18.  19.  20.]
 [ 51.  55.  53.  54.  52.  56.  57.  58.  59.  60.]
 [ 61.  65.  63.  64.  62.  66.  67.  68.  69.  70.]
 [ 71.  75.  73.  74.  72.  76.  77.  78.  79.  80.]
 [ 81.  85.  83.  84.  82.  8

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 4.</b></span> Se llama <b>matriz de Hilbert de orden $n$</b> a la matriz $H=(h_{i,j})\in\mathcal{M}_n(\mathbb{R})$ tal que $h_{i,j}=\frac{1}{i+j-1}$, para todo $i,j=1,2,\ldots,n$. Construir e imprimir una matriz de Hilbert de orden 5, así como todas sus submatrices principales (que son también matrices de Hilbert); calcular también el determinante de estas submatrices.
    </span></div>

In [38]:
# Ejercicio 4.
print("Ejercicio 4.")


Ejercicio 4.


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 5.</b></span> Se llama <b>matriz de Vandermonde de orden $n$</b> a la matriz $V=(v_{i,j})\in\mathcal{M}_n(\mathbb{K})$ tal que $v_{i,j}={\alpha_i}^{j-1}$, para todo $i,j=1,2,\ldots,n$, siendo $\alpha_i\in\mathbb{K}$, para $i=1,2,\ldots,n$; en el caso en que $\alpha_i=i$, construir e imprimir una matriz de Vandermonde de orden 5.
    <br>
    Para suprimir líneas (filas o columnas) de una matriz, se puede utilizar la función <span style="font-family: Courier">delete()</span>, cuyos tres argumentos son una matriz, la(s) línea(s) que se quieren suprimir, y <span style="font-family: Courier">axis=</span> para indicar si se suprimen filas o columnas. Por otro lado, la función <span style="font-family: Courier">inv()</span>, cuyo único argumento es una matriz cuadrada, calcula la inversa de la misma (supuesta regular).
    <br>
    Construir la matriz de cofactores de la matriz de Vandermonde anterior y comprobar que la transpuesta de la misma, dividida por su determinante, es la inversa.
</span>

In [ ]:
# Ejercicio 5.
print("Ejercicio 5.")
...